alias: Notificare Sfarsit Alerta Meteo
description: >-
  Trimite notificări pe iPhone și HTML5 când alerta meteo a trecut și senzorul
  revine la starea 'liniste'. Funcționează cu orice județ.
triggers:
  - trigger: state
    entity_id: sensor.mesaj_meteo_alba
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_arad
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_arges
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bacau
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bihor
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bistrita_nasaud
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_botosani
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_braila
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_brasov
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bucuresti
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_buzau
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_calarasi
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_caras_severin
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_cluj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_constanta
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_covasna
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_dambovita
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_dolj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_galati
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_giurgiu
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_gorj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_harghita
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_hunedoara
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_ialomita
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_iasi
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_ilfov
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_maramures
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_mehedinti
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_mures
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_neamt
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_olt
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_prahova
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_salaj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_satu_mare
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_sibiu
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_suceava
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_teleorman
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_timis
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_tulcea
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_valcea
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_vaslui
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_vrancea
    to: liniste
conditions:
  - condition: template
    value_template: >
      {{ states('sensor.avertizari_meteo_anm') not in ['unavailable', 'unknown',
      'None'] }}
  - condition: template
    value_template: |-
      {% if trigger.from_state is not none %}
        {% set old_state = trigger.from_state.state %}
        {% set old_msg = trigger.from_state.attributes.mesaj_complet | default('') %}
        {% set new_msg = trigger.to_state.attributes.mesaj_complet | default('') %}
        
        {% if old_state in ['unavailable', 'unknown'] %}
          false
        {% else %}
          {{ old_state != 'liniste' or old_msg != new_msg }}
        {% endif %}
      {% else %}
        false
      {% endif %}
actions:
  # Extrage informații din senzor
  - variables:
      mesaj_entity_id: "{{ trigger.entity_id }}"
      cod_judet: "{{ trigger.entity_id.replace('sensor.mesaj_meteo_', '') }}"
      judet_map:
        alba: "Alba"
        arad: "Arad"
        arges: "Argeș"
        bacau: "Bacău"
        bihor: "Bihor"
        bistrita_nasaud: "Bistrița-Năsăud"
        botosani: "Botoșani"
        braila: "Brăila"
        brasov: "Brașov"
        bucuresti: "București"
        buzau: "Buzău"
        calarasi: "Călărași"
        caras_severin: "Caraș-Severin"
        cluj: "Cluj"
        constanta: "Constanța"
        covasna: "Covasna"
        dambovita: "Dâmbovița"
        dolj: "Dolj"
        galati: "Galați"
        giurgiu: "Giurgiu"
        gorj: "Gorj"
        harghita: "Harghita"
        hunedoara: "Hunedoara"
        ialomita: "Ialomița"
        iasi: "Iași"
        ilfov: "Ilfov"
        maramures: "Maramureș"
        mehedinti: "Mehedinți"
        mures: "Mureș"
        neamt: "Neamț"
        olt: "Olt"
        prahova: "Prahova"
        salaj: "Sălaj"
        satu_mare: "Satu Mare"
        sibiu: "Sibiu"
        suceava: "Suceava"
        teleorman: "Teleorman"
        timis: "Timiș"
        tulcea: "Tulcea"
        valcea: "Vâlcea"
        vaslui: "Vaslui"
        vrancea: "Vrancea"
      judet_name: "{{ judet_map.get(cod_judet, cod_judet | title) }}"

  # Notificare iPhone
  - action: notify.mobile_app_iphone
    data:
      title: ✅ Alertă Meteo Finalizată
      message: >
        Nu mai sunt avertizări meteo active în {{ judet_name }}.
        Vremea s-a liniștit. ☀️
      data:
        url: /dashboard-acasa/0
        push:
          sound: default

  # Notificare HTML5 (browser desktop)
  - action: notify.html5
    data:
      title: ✅ Alertă Meteo Finalizată
      message: >
        Nu mai sunt avertizări meteo active în {{ judet_name }}.
        Vremea s-a liniștit. ☀️
      data:
        url: /dashboard-acasa/0
        tag: "alerta-meteo-{{ cod_judet }}"

mode: parallel
max: 43
