alias: Notificare Sfarsit Alerta Meteo
description: >-
  Trimite notificări pe iPhone și HTML5 când alerta meteo a trecut și senzorul
  revine la starea 'liniste'. Funcționează cu orice județ.
triggers:
  - trigger: state
    entity_id: sensor.mesaj_meteo_alba
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_arad
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_arges
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bacau
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bihor
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bistrita_nasaud
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_botosani
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_braila
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_brasov
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_bucuresti
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_buzau
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_calarasi
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_caras_severin
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_cluj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_constanta
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_covasna
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_dambovita
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_dolj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_galati
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_giurgiu
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_gorj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_harghita
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_hunedoara
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_ialomita
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_iasi
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_ilfov
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_maramures
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_mehedinti
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_mures
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_neamt
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_olt
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_prahova
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_salaj
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_satu_mare
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_sibiu
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_suceava
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_teleorman
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_timis
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_tulcea
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_valcea
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_vaslui
    to: liniste
  - trigger: state
    entity_id: sensor.mesaj_meteo_vrancea
    to: liniste
conditions:
  # Verific că entitatea triggeredă e pentru județul selectat (nu unavailable)
  - condition: template
    value_template: >
      {{ states(trigger.entity_id) not in ['unavailable', 'unknown'] and 
         state_attr(trigger.entity_id, 'mesaj_complet') is not none }}

  - condition: template
    value_template: >
      {{ states('sensor.avertizari_meteo_anm') not in ['unavailable', 'unknown',
      'None'] }}
actions:
  # Notificare iPhone
  - action: notify.mobile_app_iphone
    data:
      title: ✅ Alertă Meteo Finalizată
      message: >
        {%- set cod_judet = trigger.entity_id.replace('sensor.mesaj_meteo_', '') -%}
        Nu mai sunt avertizări meteo active. Vremea s-a liniștit. ☀️
      data:
        url: /dashboard-acasa/0
        push:
          sound: default

  # Notificare HTML5 (browser desktop)
  - action: notify.html5
    data:
      title: ✅ Alertă Meteo Finalizată
      message: >
        {%- set cod_judet = trigger.entity_id.replace('sensor.mesaj_meteo_', '') -%}
        Nu mai sunt avertizări meteo active. Vremea s-a liniștit. ☀️
      data:
        url: /dashboard-acasa/0
        tag: "alerta-meteo-{{ trigger.entity_id.replace('sensor.mesaj_meteo_', '') }}"

mode: parallel
max: 43
